// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AnalyzeFile(arg1:string):Promise<Array<any>>;

export function GetFileInfo(arg1:string):Promise<main.FileInfo>;
